[package]
name = "isolate_windows"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_NetworkManagement_WindowsFilteringPlatform", "Win32_Networking_WinSock", "Win32_Security", "Win32_System_Threading"] }

